---
apiVersion: backstage.io/v1alpha1
kind: System
metadata:
  name: itcne-portal
  description: The ITCNE Developer Portal, a Backstage application for managing software components, documentation, and developer workflows.
spec:
  owner: teacher
---
apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: backstage
  description: The ITCNE Developer Portal, a Backstage application for managing software components, documentation, and developer workflows.
  tags:
    - developer-portal
    - backstage
    - kubernetes
    - ci-cd
  links:
    - title: Developer Portal
      url: http://localhost:3000
  annotations:
    github.com/project-slug: itcne/sem05_devhub
    backstage.io/techdocs-ref: dir:.
    backstage.io/managed-by-location: url:https://github.com/itcne/sem05_devhub/blob/main/catalog-info.yaml
    backstage.io/source-location: url:https://github.com/itcne/sem05_devhub
spec:
  type: website
  owner: teacher
  lifecycle: production
  system: itcne-portal
  providesApis: []
